version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=chatbot_flask.app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatbot
    depends_on:
      - db
    networks:
      - chatbot-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatbot
    networks:
      - chatbot-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - chatbot-network

volumes:
  postgres_data:

networks:
  chatbot-network:
    driver: bridge 